services:
  db:
    image: postgres:16
    container_name: notification-service-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: real_estate_notifications
    ports:
      - "7224:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    command: 
      - "postgres"
      - "-c"
      - "log_statement=all"

volumes:
  postgres_data: